# Generated by Django 3.2 on 2024-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=5,
                verbose_name='Код подтверждения',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('user', 'Пользователь'),
                    ('moderator', 'Модератор'),
                    ('admin', 'Администратор'),
                ],
                default='user',
                max_length=20,
                null=True,
                verbose_name='Роль',
            ),
        ),
    ]
