# Generated by Django 3.2 on 2024-07-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=5,
                verbose_name='Код подтверждения',
            ),
        ),
    ]
