# Generated by Django 3.2 on 2024-07-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_title_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.review'),
        ),
    ]
